// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGHlU30Ekng1i5YIvBWV3k7jz1L-qYyMo',
    appId: '1:169461299251:web:5699f01bd3fbf147808b46',
    messagingSenderId: '169461299251',
    projectId: 'ecommerce-b98e3',
    authDomain: 'ecommerce-b98e3.firebaseapp.com',
    storageBucket: 'ecommerce-b98e3.firebasestorage.app',
    measurementId: 'G-3321VTPRR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8EjWIEpQXiIegyH3w7Ni1Ur_36aWVw-Q',
    appId: '1:169461299251:android:f6e9d30849fb91d8808b46',
    messagingSenderId: '169461299251',
    projectId: 'ecommerce-b98e3',
    storageBucket: 'ecommerce-b98e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYmLgO3JVkmpsKCJu1lwjp6xJStJGHQSA',
    appId: '1:169461299251:ios:6d7f930a5924944b808b46',
    messagingSenderId: '169461299251',
    projectId: 'ecommerce-b98e3',
    storageBucket: 'ecommerce-b98e3.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYmLgO3JVkmpsKCJu1lwjp6xJStJGHQSA',
    appId: '1:169461299251:ios:6d7f930a5924944b808b46',
    messagingSenderId: '169461299251',
    projectId: 'ecommerce-b98e3',
    storageBucket: 'ecommerce-b98e3.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGHlU30Ekng1i5YIvBWV3k7jz1L-qYyMo',
    appId: '1:169461299251:web:af3be56eb25567cd808b46',
    messagingSenderId: '169461299251',
    projectId: 'ecommerce-b98e3',
    authDomain: 'ecommerce-b98e3.firebaseapp.com',
    storageBucket: 'ecommerce-b98e3.firebasestorage.app',
    measurementId: 'G-Z6JGEVQ2KH',
  );

}